Don't require a symbol in diff() in the univariate case
In [1]: diff(x**2 + 1)
Out[1]: 2⋅x

In [2]: diff(x**2 + y)
(...)
ValueError: specify symbols to differentiate y + x**2